/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BlockHashInterface extends ethers.utils.Interface {
  functions: {
    "blockNumber()": FunctionFragment;
    "hash(uint256)": FunctionFragment;
    "last()": FunctionFragment;
    "lastBn()": FunctionFragment;
    "latest()": FunctionFragment;
    "setLast()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hash", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "last", values?: undefined): string;
  encodeFunctionData(functionFragment: "lastBn", values?: undefined): string;
  encodeFunctionData(functionFragment: "latest", values?: undefined): string;
  encodeFunctionData(functionFragment: "setLast", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "blockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "last", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastBn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLast", data: BytesLike): Result;

  events: {};
}

export class BlockHash extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BlockHashInterface;

  functions: {
    blockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    hash(bn: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    last(overrides?: CallOverrides): Promise<[string]>;

    lastBn(overrides?: CallOverrides): Promise<[BigNumber]>;

    latest(overrides?: CallOverrides): Promise<[string]>;

    setLast(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  hash(bn: BigNumberish, overrides?: CallOverrides): Promise<string>;

  last(overrides?: CallOverrides): Promise<string>;

  lastBn(overrides?: CallOverrides): Promise<BigNumber>;

  latest(overrides?: CallOverrides): Promise<string>;

  setLast(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    hash(bn: BigNumberish, overrides?: CallOverrides): Promise<string>;

    last(overrides?: CallOverrides): Promise<string>;

    lastBn(overrides?: CallOverrides): Promise<BigNumber>;

    latest(overrides?: CallOverrides): Promise<string>;

    setLast(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    hash(bn: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    last(overrides?: CallOverrides): Promise<BigNumber>;

    lastBn(overrides?: CallOverrides): Promise<BigNumber>;

    latest(overrides?: CallOverrides): Promise<BigNumber>;

    setLast(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hash(
      bn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    last(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastBn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    latest(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setLast(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
