/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  NFTInitializer,
  NFTInitializerInterface,
} from "../NFTInitializer";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
      {
        internalType: "bool",
        name: "withTokenId",
        type: "bool",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NFTInitializer__factory {
  static readonly abi = _abi;
  static createInterface(): NFTInitializerInterface {
    return new utils.Interface(_abi) as NFTInitializerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTInitializer {
    return new Contract(address, _abi, signerOrProvider) as NFTInitializer;
  }
}
